const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const root = path.join(__dirname, '..');
const output = path.join(root, 'dist/index.html');
assert(fs.existsSync(output), 'Run the reproducible build first');
const html = fs.readFileSync(output, 'utf8');
const match = html.match(/<script id="photo-data" type="application\/json">([\s\S]*?)<\/script>/);
assert(match, 'Embedded demo data must exist');
const photos = JSON.parse(match[1]);
assert.deepEqual(photos.map(p=>p.name), [1,2,3,4].map(n=>`demo-${n}.jpg`));
assert(photos.every(p=>p.src.startsWith('data:image/jpeg;base64,')));
assert(!/__\w+__/.test(html), 'No unresolved build placeholders');
assert(!/(?:\/Users\/|\/home\/|file:\/\/\/|3Q0A\d{4}|brim-lab)/i.test(html), 'No private assets or paths');
assert(!/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/.test(html), 'No network client in the editor');
assert(!/<(?:script|img|link)\b[^>]*(?:src|href)=["']https?:/i.test(html), 'No remote runtime assets');
execFileSync(process.execPath, ['scripts/build.cjs'], {cwd:root, stdio:'pipe'});
assert.equal(fs.readFileSync(output,'utf8'), html, 'Build must be deterministic on the same runtime');
console.log('PASS: reproducible standalone distribution with only generated demos; no private paths or runtime network clients.');
